[colors.bright]
black = "0x7f7f7f"
blue = "0x5c5cff"
cyan = "0x00ffff"
green = "0x00ff00"
magenta = "0xff00ff"
red = "0xff0000"
white = "0xffffff"
yellow = "0xffff00"

[colors.normal]
black = "0x000000"
blue = "0x005cff"    # More bright than xterm default 0x0000ee
cyan = "0x00cdcd"
green = "0x00cd00"
magenta = "0xcd00cd"
red = "0xcd0000"
white = "0xe5e5e5"
yellow = "0xcdcd00"

[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[font]
size = 18.0

[font.bold]
family = "Bizin Gothic NF"
style = "Bold"

[font.bold_italic]
family = "Bizin Gothic NF"
style = "Bold Italic"

[font.italic]
family = "Bizin Gothic NF"
style = "Italic"

[font.normal]
family = "Bizin Gothic NF"
style = "Regular"

[window]
option_as_alt = "Both"
# Startup Mode (changes require restart)
#
# Values for `startup_mode`:
#   - Windowed
#   - Maximized
#   - Fullscreen
#
# Values for `startup_mode` (macOS only):
#   - SimpleFullscreen
startup_mode = "Maximized"
