modmap:
  - name: Left(Right) Alt tap -> IME off(on)
    remap:
      Alt_L:
        held: Alt_L
        alone: Muhenkan
        free_hold: true # Optional, defaults to false.
      Alt_R:
        held: Alt_R
        alone: Henkan
        free_hold: true # Optional, defaults to false.
keymap:
  - name: Left(Right) Alt + space -> IME off(on)
    remap:
      Alt_R-space: Henkan
      Alt_L-space: Muhenkan
  - name: Bugfix mozc hhkb
    remap:
      zenkakuhankaku: backslash
  - name: Minimal Emacs keybind
    application:
      not: [Alacritty]
    remap:
      # Cursor
      C-b: left
      C-f: right
      C-p: up
      C-n: down
      C-leftbrace: esc
      C-a: home
      C-e: end
      C-m: enter
      C-h: backspace
      C-k: [Shift-end, Delete]
  - name: use Super as main modification kay
    application:
      not: [Alacritty]
    remap:
      Alt-a: C-a
      Alt-c: C-c
      Alt-e: C-e
      Alt-f: C-f
      Alt-k: C-k
      Alt-l: C-l
      Alt-n: C-n
      Alt-o: C-o
      Alt-q: C-q
      Alt-s: C-s
      Alt-w: C-w
      Alt-t: C-t
  - name: use Super as main modification key
    remap:
      Alt-v: C-Shift-v
  - name: move tab Alt + Shift + \{
    remap:
      Alt-Shift-leftbrace: C-Shift-tab
      Alt-Shift-rightbrace: C-tab
  - name: IME off when launcher
    remap:
      Alt_L-semicolon: [Alt_L-semicolon, Muhenkan]
  - name: KANA input like Windows in US keyboard
    remap:
      Shift-leftbrace: Shift-rightbrace
      Shift-rightbrace: Shift-backslash

